site_name: Deebot
site_description: Docs for Open Source projects related to Deebot devices from Ecovacs - but we are in no way affiliated with ECOVACS Robotics (ECOVACS)

repo_url: https://github.com/DeebotUniverse/docs
edit_uri: blob/main/docs/

theme:
  name: material
  icon:
    logo: material/robot-vacuum
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

nav:
  - Home: index.md
  - General:
      - "Country codes": general/countryCodes.md
      - FAQ: general/faq.md
  - Advanced:
      - advanced/index.md
      - MQTT:
          - advanced/mqtt/index.md
          - JSON:
              - advanced/mqtt/json/index.md
              - Commands:
                  - advanced/mqtt/json/commands/index.md
                  - General: advanced/mqtt/json/commands/general.md
                  - Stats: advanced/mqtt/json/commands/stats.md
