site_name: DeebotUniverse
site_description: Docs for Open Source projects related to Deebot devices from Ecovacs - but we are in no way affiliated with ECOVACS Robotics (ECOVACS)

repo_url: https://github.com/DeebotUniverse/docs
edit_uri: blob/main/docs/

theme:
  name: material
  icon:
    logo: material/robot-vacuum
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - mdx_truly_sane_lists
  - meta
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  # https://github.com/fralau/mkdocs_macros_plugin
  - macros:
      include_dir: include
  - search
  # https://github.com/aklajnert/mkdocs-simple-hooks
  - mkdocs-simple-hooks:
      hooks:
        on_post_page: "plugins.children_with_subtitle:insert_children_with_subtitle"

nav:
  - Home:
      - index.md
      - Projects: home/projects.md
      - Models: home/models.md
      - FAQ: home/faq.md
  - Integrations:
      - Home Assistant:
          - integrations/home-assistant/index.md
          - Setup: integrations/home-assistant/setup.md
          - Entities: integrations/home-assistant/entities.md
          - Events: integrations/home-assistant/events.md
          - Services: integrations/home-assistant/services.md
          - Issues: integrations/home-assistant/issues.md
          - Misc: integrations/home-assistant/misc.md
          - Examples:
              - Commands: integrations/home-assistant/examples/commands.md
              - UI:
                  - Simple: integrations/home-assistant/examples/ui/simple.md
                  - Advanced: integrations/home-assistant/examples/ui/advanced.md
          - Migration: integrations/home-assistant/migration.md
  - Advanced:
      - Protocols:
          - MQTT: advanced/protocols/mqtt.md
          - REST: advanced/protocols/rest.md
          - XMPP: advanced/protocols/xmpp.md
      - Data types:
          - JSON:
              - Commands:
                  - advanced/data_types/json/commands/index.md
                  - General: advanced/data_types/json/commands/general.md
                  - Advanced mode: advanced/data_types/json/commands/advanced_mode.md
                  - Auto empty: advanced/data_types/json/commands/auto_empty.md
                  - Break point: advanced/data_types/json/commands/break_point.md
                  - Carpet pressure: advanced/data_types/json/commands/carpet_pressure.md
                  - Clean count: advanced/data_types/json/commands/clean_count.md
                  - Life span: advanced/data_types/json/commands/life_span.md
                  - Map: advanced/data_types/json/commands/map.md
                  - Multimap state: advanced/data_types/json/commands/map.md
                  - Net info: advanced/data_types/json/commands/net_info.md
                  - Over the air update: advanced/data_types/json/commands/ota.md
                  - Play sound: advanced/data_types/json/commands/play_sound.md
                  - Relocate: advanced/data_types/json/commands/relocate.md
                  - Speed: advanced/data_types/json/commands/speed.md
                  - Sleep mode: advanced/data_types/json/commands/sleep_mode.md
                  - Stats: advanced/data_types/json/commands/stats.md
                  - True detect: advanced/data_types/json/commands/true_detect.md
                  - Volume: advanced/data_types/json/commands/volume.md
                  - Water: advanced/data_types/json/commands/water.md
              - Messages:
                  - advanced/data_types/json/messages/index.md
                  - General: advanced/data_types/json/messages/general.md
                  - Map: advanced/data_types/json/messages/map.md
                  - Stats: advanced/data_types/json/messages/stats.md
          - XML:
              - Commands:
                  - advanced/data_types/xml/commands/index.md
                  - General: advanced/data_types/xml/commands/general.md
                  - Clean: advanced/data_types/xml/commands/clean.md
                  - Clean speed: advanced/data_types/xml/commands/cleanSpeed.md
                  - Play sound: advanced/data_types/xml/commands/playSound.md
                  - Water: advanced/data_types/xml/commands/waterlevel.md
              - Messages:
                  - advanced/data_types/xml/messages/index.md
                  - General: advanced/data_types/xml/messages/general.md
