site_name: Deebot
site_description: Docs for Open Source projects related to Deebot devices from Ecovacs - but we are in no way affiliated with ECOVACS Robotics (ECOVACS)

repo_url: https://github.com/DeebotUniverse/docs
edit_uri: blob/main/docs/

theme:
  name: material
  icon:
    logo: material/robot-vacuum
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - admonition
  - mdx_truly_sane_lists
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Home: index.md
  - General:
      - Projects: general/projects.md
      - Models: general/models.md
      - FAQ: general/faq.md
  - Integrations:
      - Home Assistant:
          - integrations/home-assistant/index.md
          - Setup: integrations/home-assistant/setup.md
          - Services: integrations/home-assistant/services.md
          - Issues: integrations/home-assistant/issues.md
  - Advanced:
      - MQTT:
          - JSON:
              - Commands:
                  - advanced/mqtt/json/commands/index.md
                  - General: advanced/mqtt/json/commands/general.md
                  - Stats: advanced/mqtt/json/commands/stats.md
          - XML:
              - Commands:
                  - advanced/mqtt/xml/commands/index.md
                  - General: advanced/mqtt/xml/commands/general.md
