site_name: Deebot
site_description: Docs for Open Source projects related to Deebot devices from Ecovacs - but we are in no way affiliated with ECOVACS Robotics (ECOVACS)

repo_url: https://github.com/DeebotUniverse/docs

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference

nav:
  - Home: index.md
  - General:
      - "Country codes": general/countryCodes.md
      - FAQ: general/faq.md
  - Advanced:
      - Commands:
          - General: advanced/commands/general.md
          - Stats: advanced/commands/stats.md

