site_name: DeebotUniverse
site_description: Docs for Open Source projects related to Deebot devices from Ecovacs - but we are in no way affiliated with ECOVACS Robotics (ECOVACS)

repo_url: https://github.com/DeebotUniverse/docs
edit_uri: blob/main/docs/

theme:
  name: material
  icon:
    logo: material/robot-vacuum
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest

markdown_extensions:
  - admonition
  - attr_list
  - mdx_truly_sane_lists
  - tables
  - footnotes
  - toc:
      permalink: true
      permalink_title: Anchor link to this section for reference
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  # https://github.com/mondeja/mkdocs-include-markdown-plugin
  - include-markdown
  - search

nav:
  - Home:
      - index.md
      - Projects: home/projects.md
      - Models: home/models.md
      - FAQ: home/faq.md
  - Integrations:
      - Home Assistant:
          - integrations/home-assistant/index.md
          - Setup: integrations/home-assistant/setup.md
          - Entities: integrations/home-assistant/entities.md
          - Events: integrations/home-assistant/events.md
          - Services: integrations/home-assistant/services.md
          - Issues: integrations/home-assistant/issues.md
          - Misc: integrations/home-assistant/misc.md
          - Examples:
              - Commands: integrations/home-assistant/examples/commands.md
              - UI:
                  - Simple: integrations/home-assistant/examples/ui/simple.md
                  - Advanced: integrations/home-assistant/examples/ui/advanced.md
          - Migration: integrations/home-assistant/migration.md
  - Advanced:
      - MQTT:
          - JSON:
              - Commands:
                  - advanced/mqtt/json/commands/index.md
                  - General: advanced/mqtt/json/commands/general.md
                  - Map: advanced/mqtt/json/commands/map.md
                  - PlaySound: advanced/mqtt/json/commands/playSound.md
                  - Stats: advanced/mqtt/json/commands/stats.md
                  - Volume: advanced/mqtt/json/commands/volume.md
                  - Water: advanced/mqtt/json/commands/water.md
              - Messages:
                  - advanced/mqtt/json/messages/index.md
                  - Stats: advanced/mqtt/json/messages/stats.md
              - Reference:
                  - Clean modes: advanced/mqtt/json/reference/clean-modes.md
                  - Charge modes: advanced/mqtt/json/reference/charge-modes.md
                  - Power level modes: advanced/mqtt/json/reference/cleanspeed-modes.md
                  - Water level modes: advanced/mqtt/json/reference/waterlevel-modes.md
          - XML:
              - Commands:
                  - advanced/mqtt/xml/commands/index.md
                  - General: advanced/mqtt/xml/commands/general.md
                  - Clean: advanced/mqtt/xml/commands/clean.md
                  - PlaySound: advanced/mqtt/xml/commands/playSound.md
              - Reference:
                  - Clean modes: advanced/mqtt/xml/reference/clean-modes.md
                  - Charge modes: advanced/mqtt/xml/reference/charge-modes.md
                  - Power level modes: advanced/mqtt/xml/reference/cleanspeed-modes.md
                  - Water level modes: advanced/mqtt/xml/reference/waterlevel-modes.md
      - XMPP:
          - XML:
              - Commands:
                  - advanced/xmpp/xml/commands/index.md
                  - General: advanced/xmpp/xml/commands/general.md
                  - Clean: advanced/xmpp/xml/commands/clean.md
                  - PlaySound: advanced/xmpp/xml/commands/playSound.md
              - Reference:
                  - Clean modes: advanced/xmpp/xml/reference/clean-modes.md
                  - Charge modes: advanced/xmpp/xml/reference/charge-modes.md
                  - Power level modes: advanced/xmpp/xml/reference/cleanspeed-modes.md
                  - Water level modes: advanced/xmpp/xml/reference/waterlevel-modes.md
